version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: flask-webhook-viewer
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 --threads 2 app:app
